from ._base import sentence_length
from ._base import character_count
from ._base import whitespaces_count
from ._base import duplicates_character_count
from ._base import emoji_character_count
from ._base import english_character_count
from ._base import chinese_character_count
from ._base import punctuations_count
from ._base import word_count
from ._base import duplicates_word_count